services:
  database:
    container_name: database
    image: mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root_secret
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_secret
      LANG: C.UTF-8
    ports:
      - 33061:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - net
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
  ollama:
    container_name: ollama
    volumes:
      - ollama_data:/root/.ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 7869:11434
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    networks:
      - net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  bot:
    container_name: bot
    env_file: ".env"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - net
    depends_on:
      ollama:
        condition: service_started
      database:
        condition: service_started
volumes:
  mysql_data:
  ollama_data:
networks:
  net: